### ISSUE TITLE
Request: Turret Vehicle Detection

### ISSUE THREAD

**Issue by HellDragon-HK** [GreatEmerald/U2Weapons#4]
- [ ] The turrets are good but easy prey for vehicles at long range, would it be possible to allow them to spot vehicles specifically especially tanks at long distance?

**Comment by GreatEmerald** [comment]
I'd need to check how they work in XMP, but I'm pretty sure the answer is "no". They're easy prey for vehicles in XMP as well and that's the point of vehicles.

**Comment by HellDragon-HK** [comment]
I haven't played XMP so wasn't aware it had vehicles being part of U2 ok then delete this comment or do I need to do it with the close and comment?
EDIT-Maybe it should be looked at if possible because UT2004 has a lot of open ground more so than U2 has to my knowledge but I haven't played XMP so I don't know what the maps are like so can't really give a fact to back anything up.

**Comment by GreatEmerald** [comment]
Nah, I can do it too.
